# Database
dataSource.url=jdbc:jtds:sqlserver://localhost:1433/dol
dataSource.driverClassName=net.sourceforge.jtds.jdbc.Driver
dataSource.username=sa
dataSource.password=123456
dataSource.schema=dbo
dataSource.catalog=dol

# Hibernate
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.ddl_auto=none
hibernate.show_sql=true

# Web
session_timeout=10

# ClienteWS
url_webservice=localhost
port_webservice=8080

# VERNAZZA
cuit_emisor=30000000001 
logo_pdf=logo.jpg
empresa_pdf=Empresa S.A.
membrete1_pdf=Direccion 9999
membrete2_pdf=C9999ZZZ Localidad - Provincia - Argentina
cuit_pdf=CUIT 30-00000000-1
iibb_pdf=IIBB 999999-99
condicion_iva_pdf=IVA Responsable Inscripto
inicio_actividad_pdf=Inicio de Act: 01/04/1900
observaciones_generales1_pdf=
observaciones_generales2_pdf=
observaciones_generales3_pdf=
formato_pdf=factura.csv
# A4 o letter o legal
papel_pdf=A4
# portrait o landscape
orientacion_pdf=portrait
# original, duplicado y triplicado
num_copias_pdf=3
# cantidad de linas de items por página
lineas_max_pdf=30
# cantidad a la izquierda de la descripción del artículo
qty_pos_pdf=izq
# ubicación y nombre del archivo pdf a generar
salida_pdf=

# Autorizador SQL
interfaz_2001=1234
interfaz_2002=1234
interfaz_2003=1234
interfaz_2004=1234
interfaz_2005=1234
interfaz_2006=1234
interfaz_2007=1234
interfaz_9901=1234

# Parametros Ceres
actualizador_log=fews_upd_ast_fews_log_tmp
importador_log=ast_upd_fews_encabezado_tmp