log4j.rootLogger=INFO, console, file
log4j.category.org.springframework.jdbc.core.JdbcTemplate=INFO, console
log4j.logger.ar.com.boldt=INFO, file
log4j.logger.ar.com.coninf=INFO, file

#Comentario
### direct log messages to stdout ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %-5p %l - %m%n

### direct log messages to console ###
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.ImmediateFlush=true
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

### direct log messages to file ###
log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
log4j.appender.file.File=/logs/fews.log
log4j.appender.file.DatePattern=.yyyy-MM-dd.HH
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss} %-5p %c - %m%n

### log4j.rootLogger=INFO, console, consola
### log4j.logger.ar.com.boldt.conversor=ERROR, conversor
### 
### ### direct log messages to console ###
### log4j.appender.console=org.apache.log4j.ConsoleAppender
### log4j.appender.console.ImmediateFlush=true
### log4j.appender.console.layout=org.apache.log4j.PatternLayout
### log4j.appender.console.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n
### 
### ### direct log messages to file consola ###
### log4j.appender.consola=org.apache.log4j.DailyRollingFileAppender
### log4j.appender.consola.File=logs/consola.log
### log4j.appender.consola.DatePattern=.yyyy-MM-dd.HH
### log4j.appender.consola.layout=org.apache.log4j.PatternLayout
### log4j.appender.consola.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss} %-5p %c - %m%n
### 
### ### direct log messages to file conversor ###
### log4j.appender.conversor=org.apache.log4j.DailyRollingFileAppender
### log4j.appender.conversor.File=logs/conversor.log
### log4j.appender.conversor.DatePattern=.yyyy-MM-dd.HH
### log4j.appender.conversor.layout=org.apache.log4j.PatternLayout
### log4j.appender.conversor.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss} %-5p %c - %m%n