# Database
dataSource.url=jdbc:jtds:sqlserver://localhost:1433/fews
dataSource.driverClassName=net.sourceforge.jtds.jdbc.Driver
dataSource.username=sa
dataSource.password=123456
dataSource.schema=dbo
dataSource.catalog=fews

# Hibernate
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.ddl_auto=none
hibernate.show_sql=true

# Web
session_timeout=20

# Autorizador SQL
interfaz_9901=1234
interfaz_9901=4001

# Parametros Ceres
actualizador_log=fews_upd_ast_fews_log_tmp
importador_log=ast_upd_fews_encabezado_tmp

# ClienteWS
url_webservice=localhost
port_webservice=8080