url_wsaa_homo=https://wsaahomo.afip.gov.ar/ws/services/LoginCms
url_wsaa_prod=https://wsaa.afip.gov.ar/ws/services/LoginCms
url_wsfev1_homo=https://wswhomo.afip.gov.ar/wsfev1/service.asmx?WSDL
url_wsfev1_prod=https://servicios1.afip.gov.ar/wsfev1/service.asmx
url_wsfexv1_homo=https://wswhomo.afip.gov.ar/wsfexv1/service.asmx?WSDL
url_wsfexv1_prod=https://servicios1.afip.gov.ar/wsfexv1/service.asmx?WSDL
