mail_from = no_reply@vernazza.com
mail_to = facturacion@vernazza.com

mail_host = smtp.gmail.com
mail_user = facturacion@vernazza.com
mail_password = 123qweASD_
mail_auth = true
mail_starttls = true
mail_port = 465