# Database
dataSource.url=jdbc:jtds:sqlserver://localhost:1433/fews
dataSource.driverClassName=net.sourceforge.jtds.jdbc.Driver
dataSource.username=sa
dataSource.password=123qweASD
dataSource.schema=dbo
dataSource.catalog=fews

# Hibernate
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.ddl_auto=none
hibernate.show_sql=true

# Web
session_timeout=20

# Autorizador SQL
interfaz_6001=1234
interfaz_6002=1234

# Parametros Ceres
actualizador_log_6001=fews_upd_ast_fews_log_brdpn
importador_log_6001=ast_upd_fews_encabezado_brdpn
# Parametros Ceres
actualizador_log_6002=fews_upd_ast_fews_log_brdps
importador_log_6002=ast_upd_fews_encabezado_brdps

# ClienteWS
url_webservice=localhost
port_webservice=8080
endpoint_address=http://localhost:8282/doconline-ws/services/DocOnlineServicioWeb.DocOnlineServicioWebHttpSoap11Endpoint/

# Parametros filtros
dias_arranque=5

