# Database
dataSource.url=jdbc:jtds:sqlserver://localhost:1433/dol
dataSource.driverClassName=net.sourceforge.jtds.jdbc.Driver
dataSource.username=sa
dataSource.password=123456
dataSource.schema=dbo
dataSource.catalog=dol

# Hibernate
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.ddl_auto=none
hibernate.show_sql=true

# Web
session_timeout=10

# ClienteWS
url_webservice=localhost
port_webservice=8080