log4j.rootLogger=info, console

log4j.category.org.springframework.jdbc.core.JdbcTemplate=info, fileFews

log4j.logger.ar.com.boldt=info, fileFews
log4j.logger.ar.com.coninf=info, fileFews

### direct log messages to stdout ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %-5p %l - %m%n

### direct log messages to console ###
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.ImmediateFlush=true
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

### direct log messages to file ###
log4j.appender.fileFews=org.apache.log4j.DailyRollingFileAppender
log4j.appender.fileFews.File=/home/hogar/logs/fewsTimer.log
log4j.appender.fileFews.DatePattern=.yyyy-MM-dd
log4j.appender.fileFews.layout=org.apache.log4j.PatternLayout
log4j.appender.fileFews.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss} %-5p [%t] %c (%L) - %m%n
