USE 
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [CATEGORIA_FISCAL] [varchar](20) NULL
GO
SET ANSI_PADDING OFF
GO
