drop table #Pend

select CUIT_EMPRESA CE, 
	TIPO_COMPROBANTE TC, 
	PUNTO_VENTA PV, 
	min(NUMERO_COMPROBANTE) NC
into #Pend
from AST_FEWS_LOG
where RESULTADO is null or RESULTADO <> 'A'
group by CUIT_EMPRESA, TIPO_COMPROBANTE, PUNTO_VENTA

SELECT resultado, obs, cae,* FROM AST_FEWS_LOG inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC order by as_id desc 
SELECT * FROM AST_FEWS_LOG_IVA inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC order by as_id desc 
SELECT * FROM AST_FEWS_LOG_TRIBUTOS inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC order by as_id desc 

SELECT * FROM AST_FEWS_LOG_CBTE_ASOC
SELECT * FROM AST_FEWS_LOG_DATOS_OPC

/*		
DELETE AST_FEWS_LOG          FROM AST_FEWS_LOG          inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC  
DELETE AST_FEWS_LOG_IVA      FROM AST_FEWS_LOG_IVA      inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC 
DELETE AST_FEWS_LOG_TRIBUTOS FROM AST_FEWS_LOG_TRIBUTOS inner join #Pend on CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC 
*/