/****** Object:  Table [dbo].[AST_FEWS_LOG]    Script Date: 05/25/2016 10:40:21 ******/
DROP TABLE [dbo].[AST_FEWS_LOG]
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_IVA]    Script Date: 05/25/2016 10:40:21 ******/
DROP TABLE [dbo].[AST_FEWS_LOG_IVA]
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_TRIBUTOS]    Script Date: 05/25/2016 10:40:21 ******/
DROP TABLE [dbo].[AST_FEWS_LOG_TRIBUTOS]
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_DATOS_OPC]    Script Date: 05/25/2016 10:40:21 ******/
DROP TABLE [dbo].[AST_FEWS_LOG_DATOS_OPC]
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_CBTE_ASOC]    Script Date: 05/25/2016 10:40:21 ******/
DROP TABLE [dbo].[AST_FEWS_LOG_CBTE_ASOC]
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_CBTE_ASOC]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_CBTE_ASOC](
    [AS_ID] VARCHAR(20) NULL,
    [CUIT_EMPRESA] VARCHAR(20) NULL,
    [TIPO_COMPROBANTE] VARCHAR(3) NULL,
    [PUNTO_VENTA] VARCHAR(10) NULL,
    [NUMERO_COMPROBANTE] VARCHAR(20) NULL,
    [TIPO_COMPROBANTE_ASOC] VARCHAR(3),
    [PUNTO_VENTA_ASOC] VARCHAR(10) NULL,
    [NUMERO_COMPROBANTE_ASOC] VARCHAR(20) NULL,
    [CUIT_ASOC] VARCHAR(20) NULL,
    [FECHA_COMPROBANTE_ASOC] [varchar](10) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_DATOS_OPC]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_DATOS_OPC](
    [AS_ID] VARCHAR(20) NULL,
    [CUIT_EMPRESA] VARCHAR(20) NULL,
    [TIPO_COMPROBANTE] VARCHAR(3) NULL,
    [PUNTO_VENTA] VARCHAR(10) NULL,
    [NUMERO_COMPROBANTE] VARCHAR(20) NULL,
    [ID_OPCIONAL] INTEGER NULL,
    [VALOR] VARCHAR(200) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_TRIBUTOS]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_TRIBUTOS](
	[AS_ID] [varchar](20) NULL,
	[CUIT_EMPRESA] [varchar](20) NULL,
	[TIPO_COMPROBANTE] [varchar](3) NULL,
	[PUNTO_VENTA] [varchar](10) NULL,
	[NUMERO_COMPROBANTE] [varchar](20) NULL,
	[TRIBUTO_ID] [varchar](20) NULL,
	[DESCRPTION] [varchar](50) NULL,
	[PORCENTAJE] [numeric](12, 4) NULL,
	[NETO_GRAVADO] [varchar](20) NULL,
	[IMPORTE] [varchar](20) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_IVA]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_IVA](
	[AS_ID] [varchar](20) NULL,
	[CUIT_EMPRESA] [varchar](20) NULL,
	[TIPO_COMPROBANTE] [varchar](3) NULL,
	[PUNTO_VENTA] [varchar](10) NULL,
	[NUMERO_COMPROBANTE] [varchar](20) NULL,
	[PORCENTAJE] [numeric](12, 4) NULL,
	[NETO_GRAVADO] [varchar](20) NULL,
	[IMPORTE] [varchar](20) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[AST_FEWS_LOG]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG](
	[CUIT_EMPRESA] [varchar](20) NULL,
	[TIPODOC_CLIENTE] [varchar](20) NULL,
	[NRODOC_CLIENTE] [varchar](20) NULL,
	[AS_ID] [varchar](20) NULL,
	[TIPO_COMPROBANTE] [varchar](3) NULL,
	[PUNTO_VENTA] [varchar](10) NULL,
	[NUMERO_COMPROBANTE] [varchar](20) NULL,
	[FECHA_COMPROBANTE] [varchar](10) NULL,
	[FECHA_VENC_PAGO] [varchar](10) NULL,
	[CONCEPTO_FACTURA] [varchar](2) NULL,
	[MONEDA] [varchar](20) NULL,
	[MONEDA_CTZ] [varchar](20) NULL,
	[IMPORTE_TOTAL] [varchar](20) NULL,
	[NETO_NOGRAVADO] [varchar](20) NULL,
	[NETO_GRAVADO] [varchar](20) NULL,
	[NETO_EXENTO] [varchar](20) NULL,
	[IVA_TOTAL] [varchar](20) NULL,
	[TRIBUTOS_TOTAL] [varchar](20) NULL,
	[CAE] [varchar](20) NULL,
	[FECHA_VENCIMIENTO] [varchar](10) NULL,
	[CODIGO] [varchar](10) NULL,
	[DESCRIPCION] [varchar](1000) NULL,
	[OBSERVACION] [varchar](1000) NULL,
	[EXCEPCION_WSAA] [varchar](1000) NULL,
	[EXCEPCION_WSFEV1] [varchar](1000) NULL,
	[RESULTADO] [varchar](10) NULL,
	[ERR_MSG] [varchar](1000) NULL,
	[OBS] [varchar](1000) NULL,
	[XML_REQUEST_AFIP] [text] NULL,
	[XML_RESPONSE_AFIP] [text] NULL,
	[QR] [varbinary](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
