USE [master]
GO

/****** Object:  Database [FEWS]    Script Date: 10/31/2019 20:53:35 ******/
CREATE DATABASE [FEWS] ON  PRIMARY 
( NAME = N'fews', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\FEWS1.mdf' , SIZE = 100000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10000KB )
 LOG ON 
( NAME = N'fews_log_1', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\FEWS1_0.ldf' , SIZE = 10000KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [FEWS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FEWS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FEWS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FEWS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FEWS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FEWS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FEWS] SET ARITHABORT OFF 
GO

ALTER DATABASE [FEWS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FEWS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FEWS] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [FEWS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FEWS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FEWS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FEWS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FEWS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FEWS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FEWS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FEWS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FEWS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FEWS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FEWS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FEWS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FEWS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FEWS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FEWS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FEWS] SET  READ_WRITE 
GO

ALTER DATABASE [FEWS] SET RECOVERY FULL 
GO

ALTER DATABASE [FEWS] SET  MULTI_USER 
GO

ALTER DATABASE [FEWS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FEWS] SET DB_CHAINING OFF 
GO


