USE [fews]
GO

/****** Object:  Table [dbo].[FEWS_TIPO_COMPROBANTE_AFIP]    Script Date: 01/03/2023 10:29:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FEWS_TIPO_COMPROBANTE_AFIP]') AND type in (N'U'))
DROP TABLE [dbo].[FEWS_TIPO_COMPROBANTE_AFIP]
GO

/****** Object:  Table [dbo].[FEWS_TIPO_COMPROBANTE_AFIP]    Script Date: 01/03/2023 10:29:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FEWS_TIPO_COMPROBANTE_AFIP](
	[id] [int] IDENTITY(0,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[descripcion] [varchar](100) NOT NULL,
	[prefijo] [varchar](20) NOT NULL,
	[id_afip] [int] NOT NULL,
 CONSTRAINT [PK_FEWS_TIPO_COMPROBANTE_AFIP] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Carga de Datos Inicial ******/
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_A',1,'FACTURA A','FA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_B',6,'FACTURA B','FB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_C',11,'FACTURA C','FC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_CREDITO_A',201,'FAC. DE CREDITO A','FCA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_CREDITO_B',206,'FAC. DE CREDITO B','FCB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_CREDITO_C',211,'FAC. DE CREDITO C','FCC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_A',2,'NOTA DE DEBITO A','NDA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_B',7,'NOTA DE DEBITO B','NDB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_C',12,'NOTA DE DEBITO C','NDC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_CREDITO_A',202,'N. DEBITO DE CREDITO A','NDCA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_CREDITO_B',207,'N. DEBITO DE CREDITO B','NDCB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_CREDITO_C',212,'N. DEBITO DE CREDITO C','NDCC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_A',3,'NOTA DE CREDITO A','NCA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_B',8,'NOTA DE CREDITO B','NCB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_C',13,'NOTA DE CREDITO C','NCC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_CREDITO_A',203,'N. CREDITO DE CREDITO A','NCCA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_CREDITO_B',208,'N. CREDITO DE CREDITO B','NCCB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_CREDITO_C',213,'N. CREDITO DE CREDITO C','NCCC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('RECIBO_A',4,'RECIBO A','RA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('RECIBO_B',9,'RECIBO B','RB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('RECIBO_C',15,'RECIBO C','RC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_VENTA_CONTADO_A',5,'N. V. CONTADO A','VA')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_VENTA_CONTADO_B',10,'N. V. CONTADO B','VB')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_VENTA_CONTADO_C',16,'N. V. CONTADO C','VC')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_E',19,'FACTURA E','FE')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_E',20,'NOTA DE DEBITO E','NDE')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_E',21,'NOTA DE CREDITO E','NCE')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_E_PS',22,'FACTURA E PERMISO SIMPLIFICADO','FEPS')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('FACTURA_M',51,'FACTURA M','FM')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_DEBITO_M',52,'NOTA DE DEBITO M','NDM')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_CREDITO_M',53,'NOTA DE CREDITO A','NCM')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('RECIBO_M',54,'RECIBO M','RM')
insert into FEWS_TIPO_COMPROBANTE_AFIP (NOMBRE, ID_AFIP, DESCRIPCION, PREFIJO) values ('NOTA_VENTA_CONTADO_M',55,'N. V. CONTADO M','VM')
