/****** Object:  Table [dbo].[AST_FEWS_LOG_DETALLE]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_DETALLE](
    [AS_ID] VARCHAR(20) NULL,
    [CUIT_EMPRESA] VARCHAR(20) NULL,
    [TIPO_COMPROBANTE] VARCHAR(3) NULL,
    [PUNTO_VENTA] VARCHAR(10) NULL,
    [NUMERO_COMPROBANTE] VARCHAR(20) NULL,
	[CODIGO] [varchar](30) NULL,
	[DESCRIPCION] [varchar](4000) NULL,
	[CANTIDAD] [varchar](20) NULL,
	[UNIDAD_MEDIDA] [smallint] NULL,
	[PRECIO] [varchar](20) NULL,
	[IMPORTE_TOTAL] [varchar](20) NULL,
	[BONIFICACION] [varchar](20) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG_PERMISO]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AST_FEWS_LOG_PERMISO](
    [AS_ID] VARCHAR(20) NULL,
    [CUIT_EMPRESA] VARCHAR(20) NULL,
    [TIPO_COMPROBANTE] VARCHAR(3) NULL,
    [PUNTO_VENTA] VARCHAR(10) NULL,
    [NUMERO_COMPROBANTE] VARCHAR(20) NULL,
	[ID_PERMISO] [varchar](16) NULL,
	[DST_MERCADERIA] [smallint] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[AST_FEWS_LOG]    Script Date: 05/25/2016 10:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [TIPO_EXPORTACION] [varchar](1) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [PERMISO_EXISTENTE] [varchar](1) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [DST_COMPROBANTE] [varchar](3) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [CLIENTE] [varchar](200) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [CUIT_PAIS_CLIENTE] [varchar](20) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [DOMICILIO_CLIENTE] [varchar](300) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [ID_IMPOSITIVO] [varchar](50) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [OBS_COMERCIALES] [varchar](1000) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [OBS_GENERALES] [varchar](1000) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [FORMA_PAGO] [varchar](50) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [INCOTERMS] [varchar](3) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [INCOTERMS_DS] [varchar](20) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [IDIOMA_COMPROBANTE] [varchar](1) NULL

ALTER TABLE [dbo].[AST_FEWS_LOG] 
	ADD [EXCEPCION_WSFEXV1] [varchar](1000) NULL
GO
SET ANSI_PADDING OFF
GO
