/* ---------------------------------------------------------------------- */
/* Add table "DIRECCIONES_CLIENTES"                                       */
/* ---------------------------------------------------------------------- */
CREATE TABLE [dbo].[DIRECCIONES_CLIENTES] (
    [ID_DIRECCION] BIGINT IDENTITY(1,1) NOT NULL,
    [CALLE] VARCHAR(100) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [NUMERO] VARCHAR(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [PISO] VARCHAR(5) COLLATE Modern_Spanish_CI_AS,
    [DEPARTAMENTO] VARCHAR(5) COLLATE Modern_Spanish_CI_AS,
    [ID_LOCALIDAD] BIGINT NOT NULL,
    [LOCALIDAD_ALTERNATIVA] VARCHAR(80) COLLATE Modern_Spanish_CI_AS,
    [COD_POSTAL] VARCHAR(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
    CONSTRAINT [PK__DIRECCIO__FC7E9E8E267ABA7A] PRIMARY KEY CLUSTERED ([ID_DIRECCION])
)
GO

ALTER TABLE [dbo].[CLIENTES] ADD CONSTRAINT [FK_CLIENTES_DIRECCIONES_CLIENTES] 
    FOREIGN KEY ([ID_DIRECCION]) REFERENCES [dbo].[DIRECCIONES_CLIENTES] ([ID_DIRECCION])
GO

ALTER TABLE [dbo].[DIRECCIONES_CLIENTES] ADD CONSTRAINT [FK_DIRECCIONES_LOCALIDAD] 
    FOREIGN KEY ([ID_LOCALIDAD]) REFERENCES [dbo].[LOCALIDADES] ([ID_LOCALIDAD])
GO
