USE [DocOnline 2015 10 19]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOG_TRANSACCIONES_REGISTROS_TRANSACCIONES]') AND parent_object_id = OBJECT_ID(N'[dbo].[LOG_TRANSACCIONES]'))
ALTER TABLE [dbo].[LOG_TRANSACCIONES] DROP CONSTRAINT [FK_LOG_TRANSACCIONES_REGISTROS_TRANSACCIONES]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOG_TRANSACCIONES_TIPOS_TRANSACCIONES]') AND parent_object_id = OBJECT_ID(N'[dbo].[LOG_TRANSACCIONES]'))
ALTER TABLE [dbo].[LOG_TRANSACCIONES] DROP CONSTRAINT [FK_LOG_TRANSACCIONES_TIPOS_TRANSACCIONES]
GO

USE [DocOnline 2015 10 19]
GO

/****** Object:  Table [dbo].[LOG_TRANSACCIONES]    Script Date: 10/19/2015 13:59:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOG_TRANSACCIONES]') AND type in (N'U'))
DROP TABLE [dbo].[LOG_TRANSACCIONES]
GO

USE [DocOnline 2015 10 19]
GO

/****** Object:  Table [dbo].[LOG_TRANSACCIONES]    Script Date: 10/19/2015 13:59:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOG_TRANSACCIONES](
	[ID_LOG_TRANSACCION] [bigint] IDENTITY(1,1) NOT NULL,
	[F_INICIO_OPERACION] [datetime] NOT NULL,
	[F_FIN_OPERACION] [datetime] NOT NULL,
	[XML_ENTRADA] [text] NULL,
	[XML_SALIDA] [text] NULL,
	[ID_TIPO_TRANSACCION] [bigint] NOT NULL,
	[ID_REGISTRO_TRANSACCION] [bigint] NOT NULL,
 CONSTRAINT [PK_LOG_TRANSACCIONES] PRIMARY KEY CLUSTERED 
(
	[ID_LOG_TRANSACCION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[LOG_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_LOG_TRANSACCIONES_REGISTROS_TRANSACCIONES] FOREIGN KEY([ID_REGISTRO_TRANSACCION])
REFERENCES [dbo].[REGISTROS_TRANSACCIONES] ([ID_REGISTRO_TRANSACCION])
GO

ALTER TABLE [dbo].[LOG_TRANSACCIONES] CHECK CONSTRAINT [FK_LOG_TRANSACCIONES_REGISTROS_TRANSACCIONES]
GO

ALTER TABLE [dbo].[LOG_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_LOG_TRANSACCIONES_TIPOS_TRANSACCIONES] FOREIGN KEY([ID_TIPO_TRANSACCION])
REFERENCES [dbo].[TIPOS_TRANSACCIONES] ([ID_TIPO_TRANSACCION])
GO

ALTER TABLE [dbo].[LOG_TRANSACCIONES] CHECK CONSTRAINT [FK_LOG_TRANSACCIONES_TIPOS_TRANSACCIONES]
GO


