USE [DocOnline 2015 10 19]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGISTROS_TRANSACCIONES_INTERFACES]') AND parent_object_id = OBJECT_ID(N'[dbo].[REGISTROS_TRANSACCIONES]'))
ALTER TABLE [dbo].[REGISTROS_TRANSACCIONES] DROP CONSTRAINT [FK_REGISTROS_TRANSACCIONES_INTERFACES]
GO

USE [DocOnline 2015 10 19]
GO

/****** Object:  Table [dbo].[REGISTROS_TRANSACCIONES]    Script Date: 10/19/2015 14:00:47 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REGISTROS_TRANSACCIONES]') AND type in (N'U'))
DROP TABLE [dbo].[REGISTROS_TRANSACCIONES]
GO

USE [DocOnline 2015 10 19]
GO

/****** Object:  Table [dbo].[REGISTROS_TRANSACCIONES]    Script Date: 10/19/2015 14:00:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[REGISTROS_TRANSACCIONES](
	[ID_REGISTRO_TRANSACCION] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_INTERFAZ] [bigint] NOT NULL,
	[ID_PUNTO_VENTA] [bigint] NULL,
	[F_TRANSACCION] [datetime] NOT NULL,
	[COD_TRANSACCION] [int] NOT NULL,
	[DATOS_TRANSACCION] [varbinary](max) NOT NULL,
	[SERVICIO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_REGISTROS_TRANSACCIONES] PRIMARY KEY CLUSTERED 
(
	[ID_REGISTRO_TRANSACCION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[REGISTROS_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_REGISTROS_TRANSACCIONES_INTERFACES] FOREIGN KEY([ID_INTERFAZ])
REFERENCES [dbo].[INTERFACES] ([ID_INTERFAZ])
GO

ALTER TABLE [dbo].[REGISTROS_TRANSACCIONES] CHECK CONSTRAINT [FK_REGISTROS_TRANSACCIONES_INTERFACES]
GO


