
update TMP_ADMIFARM.dbo.AST_FEWS_LOG
set FECHA_COMPROBANTE='20160526' 

select CUIT_EMPRESA, TIPO_COMPROBANTE, PUNTO_VENTA, min(NUMERO_COMPROBANTE) NUMERO_COMPROBANTE, CONVERT(int, 0) ID_CONSOLA
into #pen
from TMP_ADMIFARM.dbo.AST_FEWS_LOG
where RESULTADO is null or RESULTADO <> 'A'
group by CUIT_EMPRESA, TIPO_COMPROBANTE, PUNTO_VENTA

SET @ID_CONSOLA=ISNULL(
	(SELECT ID 
	FROM FEWS_ENCABEZADO CONSOLA, TMP_ADMIFARM.dbo.AST_FEWS_LOG 
	WHERE AST_FEWS_LOG.AS_ID=@@as_id AND
		CONSOLA.CUIT      =AST_FEWS_LOG.CUIT_EMPRESA       COLLATE DATABASE_DEFAULT AND
		CONSOLA.CONCEPTO  =AST_FEWS_LOG.CONCEPTO_FACTURA   COLLATE DATABASE_DEFAULT AND
		CONSOLA.FECHA_CBTE=AST_FEWS_LOG.FECHA_COMPROBANTE  COLLATE DATABASE_DEFAULT AND
		CONSOLA.TIPO_CBTE =AST_FEWS_LOG.TIPO_COMPROBANTE   COLLATE DATABASE_DEFAULT AND
		CONSOLA.PUNTO_VTA =AST_FEWS_LOG.PUNTO_VENTA        COLLATE DATABASE_DEFAULT AND	
		CONSOLA.CBTE_NRO  =AST_FEWS_LOG.NUMERO_COMPROBANTE COLLATE DATABASE_DEFAULT AND
		CONSOLA.TIPO_DOC  =AST_FEWS_LOG.TIPODOC_CLIENTE    COLLATE DATABASE_DEFAULT AND
		CONSOLA.NRO_DOC   =AST_FEWS_LOG.NRODOC_CLIENTE     COLLATE DATABASE_DEFAULT AND
		CONSOLA.IMP_TOTAL =AST_FEWS_LOG.IMPORTE_TOTAL	   COLLATE DATABASE_DEFAULT)
	,-1)

IF  @ID_CONSOLA = -1
BEGIN
		INSERT INTO FEWS.DBO.FEWS_ENCABEZADO (
			CUIT,
			TIPO_DOC,
			NRO_DOC,
			TIPO_CBTE,
			PUNTO_VTA,
			CBTE_NRO,
			FECHA_CBTE,
			CONCEPTO,
			MONEDA_ID,
			MONEDA_CTZ,
			IMP_TOTAL,
			IMP_NETO,
			IMP_TOT_CONC,
			IMP_OP_EX,
			IMP_IVA,
			IMP_TRIB)

		SELECT 
			CUIT_EMPRESA,
			TIPODOC_CLIENTE,
			NRODOC_CLIENTE,
			TIPO_COMPROBANTE,
			PUNTO_VENTA,
			NUMERO_COMPROBANTE,
			FECHA_COMPROBANTE,
			CONCEPTO_FACTURA,
			MONEDA,
			MONEDA_CTZ,
			IMPORTE_TOTAL,
			NETO_GRAVADO,
			NETO_NOGRAVADO,
			NETO_EXENTO,
			IVA_TOTAL,
			TRIBUTOS_TOTAL
		FROM TMP_ADMIFARM.dbo.AST_FEWS_LOG
		WHERE AS_ID=@@AS_ID


	--
	-- OBTIENE EL ID DE LA CONSOLA
	---
	SET @ID_CONSOLA=(SELECT ID FROM FEWS_ENCABEZADO AS CONSOLA, TMP_ADMIFARM.dbo.AST_FEWS_LOG
						WHERE	AST_FEWS_LOG.AS_ID=@@as_id AND
						CONSOLA.CUIT= AST_FEWS_LOG.CUIT_EMPRESA COLLATE DATABASE_DEFAULT AND
						CONSOLA.CONCEPTO=AST_FEWS_LOG.CONCEPTO_FACTURA  COLLATE DATABASE_DEFAULT AND
						CONSOLA.FECHA_CBTE=AST_FEWS_LOG.FECHA_COMPROBANTE COLLATE DATABASE_DEFAULT AND
						CONSOLA.TIPO_CBTE=AST_FEWS_LOG.TIPO_COMPROBANTE  COLLATE DATABASE_DEFAULT AND
						CONSOLA.PUNTO_VTA=AST_FEWS_LOG.PUNTO_VENTA COLLATE DATABASE_DEFAULT AND	
						CONSOLA.CBTE_NRO=AST_FEWS_LOG.NUMERO_COMPROBANTE COLLATE DATABASE_DEFAULT AND
						CONSOLA.TIPO_DOC=AST_FEWS_LOG.TIPODOC_CLIENTE COLLATE DATABASE_DEFAULT AND
						CONSOLA.NRO_DOC=AST_FEWS_LOG.NRODOC_CLIENTE COLLATE DATABASE_DEFAULT AND
						CONSOLA.IMP_TOTAL=AST_FEWS_LOG.IMPORTE_TOTAL	COLLATE DATABASE_DEFAULT
				)
				


	---
	--- INSERTA EN FEWS_IVA
	-----

	-- SELECT * FROM [FNNGS-TEST-01].FEWS.DBO.FEWS_IVA
	INSERT INTO FEWS_IVA(
		ID,
		IVA_ID,
		BASE_IMP,
		IMPORTE)

	select
		ID=@ID_CONSOLA ,
		IVA_ID= CASE AST_FEWS_LOG_IVA.PORCENTAJE
					WHEN 10.5 THEN	4
					WHEN 21 THEN	5
					WHEN 27 THEN	6
				END ,
		BASE_IMP=AST_FEWS_LOG_IVA.NETO_GRAVADO,
		IMPORTE=AST_FEWS_LOG_IVA.IMPORTE
	from TMP_ADMIFARM.dbo.AST_FEWS_LOG_IVA
	WHERE AS_ID=@@AS_ID

	---
	--- INSERTA E FEWS_TRIBUTO
	-----

	-- SELECT * FROM [FNNGS-TEST-01].FEWS.DBO.FEWS_TRIBUTO
	INSERT INTO FEWS_TRIBUTO(
		ID,
		TRIBUTO_ID,
		TRIBUTO_DESC,
		IMPORTE)

	select
		ID=@ID_CONSOLA ,
		TRIBUTO_ID= AST_FEWS_LOG_TRIBUTOS.TRIBUTO_ID ,
		TRIBUTO_DESC=AST_FEWS_LOG_TRIBUTOS.DESCRPTION,
		IMPORTE=AST_FEWS_LOG_TRIBUTOS.IMPORTE
	from TMP_ADMIFARM.dbo.AST_FEWS_LOG_TRIBUTOS
	WHERE AS_ID=@@AS_ID
END

update fews_encabezado
set cbte_nro = right('00000000'+convert(varchar(8), convert(int, cbte_nro)-(case when tipo_cbte=1 then 565 else 423 end)), 8)
where cbte_nro>(case when tipo_cbte=1 then 565 else 423 end)

