--INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
--(2,'URL_WSAA_HOMO','WSAA para Homologación','Direccion webservice de autenticación para Homologación AFIP')
--INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
--(3,'URL_WSAA_PROD','WSAA para Producción','Dirección webservice de autenticación para Producción AFIP')
--INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
--(4,'URL_WSFEV1_HOMO','WSFEV1 para Homologación','Direccion webservice de Factura Electrónica para Homologación AFIP')
--INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
--(5,'URL_WSFEV1_PROD','WSFEV1 para Producción','Direccion webservice de Factura Electrónica para Producción AFIP')
INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
(6,'_PROXY_','Proxy de conexión','Dirección Proxy para conexión a Internet')
INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
(7,'MODO_INTRFZ_1001','Modo para 1001','Flag de Modo de Trabajo para Interfaz 1001 [HOMO|PROD]')
INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
(8,'MODO_INTRFZ_1002','Modo para 1002','Flag de Modo de Trabajo para Interfaz 1002 [HOMO|PROD]')
INSERT INTO [DocOnline].[dbo].[PARAMETROS] ([ID_PARAMETRO],[PARAMETRO],[DESCRIPCION],[TXT_AYUDA]) VALUES
(9,'MODO_INTRFZ_1','Modo para 1','Flag de Modo de Trabajo para Interfaz 1 [HOMO|PROD]')
GO
--INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
--(2,2,  'https://wsaahomo.afip.gov.ar/ws/services/LoginCms',      '2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
--INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
--(3,3,  'https://wsaa.afip.gov.ar/ws/services/LoginCms',          '2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
--INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
--(4,4,  'https://wswhomo.afip.gov.ar/wsfev1/service.asmx?WSDL',   '2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
--INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
--(5,5,  'https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL','2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
(6,6,  '','2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
(7,7,  'PROD','2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
(8,8,  'PROD','2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
INSERT INTO [DocOnline].[dbo].[PARAMETROS_VALOR] ([ID_PARAMETRO_VALOR],[ID_PARAMETRO],[VALOR],[F_VIGENCIA_DESDE],[F_VIGENCIA_HASTA],[ID_PROVINCIA]) VALUES
(9,9,  'HOMO','2015-01-01 00:00:00.000','9999-09-09 00:00:00.000',0)
GO
