select CUIT_EMPRESA CE, 
	TIPO_COMPROBANTE TC, 
	PUNTO_VENTA PV, 
	min(NUMERO_COMPROBANTE) NC, 
	convert(int, TIPO_COMPROBANTE ) NTC, 
	convert(int, PUNTO_VENTA) NPV, 
	convert(int, min(NUMERO_COMPROBANTE)) NNC, 
	0 IDC
	, (select top 1 id_interfaz from INTERFACES where CUIT_SUSCRIPCION=CUIT_EMPRESA COLLATE DATABASE_DEFAULT) ID_INTERFAZ
from TMP_FINN.dbo.AST_FEWS_LOG
where RESULTADO is null or RESULTADO <> 'A'
group by CUIT_EMPRESA, TIPO_COMPROBANTE, PUNTO_VENTA

select *
from TMP_FINN.dbo.AST_FEWS_LOG
order by TIPO_COMPROBANTE desc, PUNTO_VENTA, NUMERO_COMPROBANTE desc

select *
from TMP_FINN.dbo.AST_FEWS_LOG_IVA
order by TIPO_COMPROBANTE desc, PUNTO_VENTA, NUMERO_COMPROBANTE desc

select *
from TMP_FINN.dbo.AST_FEWS_LOG_TRIBUTOS
order by TIPO_COMPROBANTE desc, PUNTO_VENTA, NUMERO_COMPROBANTE desc

--exec AST_UPD_FEWS_ENCABEZADO_MACOR 

SELECT resultado, obs, cae,* FROM TMP_FINN.dbo.AST_FEWS_LOG order by as_id desc 


/*

			DELETE FROM AST_FEWS_LOG WHERE CUIT_EMPRESA=CE and TIPO_COMPROBANTE=TC and PUNTO_VENTA=PV and NUMERO_COMPROBANTE=NC
			DELETE FROM AST_FEWS_LOG_IVA WHERE AS_ID=@@AS_ID
			DELETE FROM AST_FEWS_LOG_TRIBUTOS WHERE AS_ID=@@AS_ID
			
delete from TMP_FINN.dbo.AST_FEWS_LOG where as_id in (1487249,1487242)
delete from TMP_FINN.dbo.AST_FEWS_LOG_TRIBUTOS where as_id in (1487249,1487242)
delete from TMP_FINN.dbo.AST_FEWS_LOG_IVA where as_id in (1487249,1487242)
*/
