exec INS_SECCION 'Administración', 1, 'SEC_ADM', ''
exec INS_SECCION 'Clientes', 2, 'SEC_CLI', ''
exec INS_SECCION 'Movimientos', 3, 'SEC_MOV', ''
exec INS_SECCION 'Ayuda', 4, 'SEC_HLP', ''

exec INS_ITEM 'Usuarios', 'SI_ADM_USR', 1, '/secure/usuarios/administracion.xhtml', 'admin-icon-blue', Null, 'Administración'
exec INS_ITEM 'Configuración', 'SI_CFG_MOD', 2, '/secure/configuracion/configuracion.xhtml', 'ui-icon-contact', Null, 'Administración'
exec INS_ITEM 'Log de Operaciones', 'SI_ADM_LOG', 3, '/secure/administracion/log.xhtml', 'ui-icon-contact', Null, 'Administración'
exec INS_ITEM 'Gestión clientes', 'SI_CLI_ABM', 1, '/secure/clientes/clientes.xhtml', 'ui-icon-person', Null, 'Clientes'
exec INS_ITEM 'Reporte', 'SI_CLI_TOT', 2, '/secure/clientes/clienteReporteTotal.xhtml', 'ui-icon-person', Null, 'Clientes'
exec INS_ITEM 'Reporte Movimientos', 'SI_CUE_MOV', 1, '/secure/cuentas/movimientos.xhtml', 'ui-icon-contact', Null, 'Movimientos'
exec INS_ITEM 'Ajuste Manual', 'SI_CUE_AJU', 2, '/secure/cuentas/ajusteManual.xhtml', 'ui-icon-wrench', Null, 'Movimientos'
exec INS_ITEM 'Exportación', 'SI_CUE_EXP', 3, '/secure/cuentas/exportaMovimientos.xhtml', 'ui-icon-disk', Null, 'Movimientos'

exec INS_ITEM_ROL 'SI_ADM_USR', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CUE_AJU', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CLI_ABM', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CFG_MOD', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CUE_MOV', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CUE_HLP', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CUE_EXP', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_ADM_LOG', 'ROLE_ADMIN'
exec INS_ITEM_ROL 'SI_CLI_TOT', 'ROLE_ADMIN'
