select * from TMP_ADMIFARM.dbo.AST_FEWS_LOG where CUIT_EMPRESA = '30711897581' and PUNTO_VENTA='0002' and TIPO_COMPROBANTE='06' order by CUIT_EMPRESA, TIPO_COMPROBANTE, PUNTO_VENTA, NUMERO_COMPROBANTE
select * from FEWS_ENCABEZADO

select * from FEWS_XML
select * from FEWS_IVA
select * from FEWS_TRIBUTO
